"""Create analysis_records table

Revision ID: 05e79d53b42e
Revises: 
Create Date: 2025-07-28 19:56:20.756765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05e79d53b42e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='內部連續ID'),
    sa.Column('analysis_id', sa.UUID(), nullable=False, comment='對外分析記錄識別碼'),
    sa.Column('content', sa.Text(), nullable=False, comment='Line文案內容'),
    sa.Column('target_audience', sa.String(length=50), nullable=False, comment='目標受眾'),
    sa.Column('send_scenario', sa.String(length=50), nullable=False, comment='發送場景'),
    sa.Column('attractiveness', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='吸引力評分 (1.0-10.0)'),
    sa.Column('readability', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='可讀性評分 (1.0-10.0)'),
    sa.Column('line_compatibility', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='Line平台相容性評分 (1.0-10.0)'),
    sa.Column('overall_score', sa.DECIMAL(precision=3, scale=1), nullable=True, comment='整體評分 (1.0-10.0)'),
    sa.Column('sentiment', sa.String(length=100), nullable=True, comment='情感傾向分析'),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='改善建議列表'),
    sa.Column('ai_model_used', sa.String(length=100), nullable=True, comment='使用的AI模型名稱'),
    sa.Column('processing_time', sa.DECIMAL(precision=6, scale=3), nullable=True, comment='處理時間(秒)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='處理狀態'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='錯誤訊息'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_records')
    # ### end Alembic commands ###
